# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x13logservice_protocol\"%\n\nLogRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\")\n\x0bLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"\x1c\n\x08Messages\x12\x10\n\x08messages\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2\xa7\x01\n\nLogService\x12O\n\nLogMessage\x12\x1f.logservice_protocol.LogRequest\x1a .logservice_protocol.LogResponse\x12H\n\x0bGetMessages\x12\x1a.logservice_protocol.Empty\x1a\x1d.logservice_protocol.Messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=34
  _globals['_LOGREQUEST']._serialized_end=71
  _globals['_LOGRESPONSE']._serialized_start=73
  _globals['_LOGRESPONSE']._serialized_end=114
  _globals['_MESSAGES']._serialized_start=116
  _globals['_MESSAGES']._serialized_end=144
  _globals['_EMPTY']._serialized_start=146
  _globals['_EMPTY']._serialized_end=153
  _globals['_LOGSERVICE']._serialized_start=156
  _globals['_LOGSERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
