### Test: GET request to facade-service
# This triggers facade_service to fetch logs from logging_service
# and static text from messages_service, then combine the responses

GET http://127.0.0.1:8000/facade-service
Accept: application/json

###

### Test: GET request to logging-service (direct check of stored messages)

GET http://127.0.0.1:8001/logging-service
Accept: application/json

###

### Test: GET request to messages-service (direct check of static text)

GET http://127.0.0.1:8002/message/
Accept: application/json
