services:

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8501:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    networks:
      - lab5-network

  consul-init:
    image: alpine/curl
    depends_on:
      - consul
    command: |
      sh -c '
        until curl -f ${CONSUL_HTTP_ADDR}/v1/status/leader; do
          echo "Waiting for Consul to be ready..."
          sleep 1
        done
        echo "Consul is ready. Pushing configurations from .env..."

        # Hazelcast configuration
        if [ -n "${HAZELCAST_NODES}" ]; then
          curl -X PUT -d "${HAZELCAST_NODES}" ${CONSUL_HTTP_ADDR}/v1/kv/hazelcast/members
          echo "Pushed hazelcast/members: ${HAZELCAST_NODES}"
        else
          echo "HAZELCAST_NODES not set in .env."
        fi
        if [ -n "${CLUSTER_NAME}" ]; then
          curl -X PUT -d "${CLUSTER_NAME}" ${CONSUL_HTTP_ADDR}/v1/kv/hazelcast/cluster_name
          echo "Pushed hazelcast/cluster_name: ${CLUSTER_NAME}"
        else
          echo "CLUSTER_NAME not set in .env."
        fi

        echo "Hazelcast configuration push complete."

        echo "Pushing Kafka configuration from .env..."

        # Kafka bootstrap servers
        if [ -n "${KAFKA_BOOTSTRAP_SERVERS}" ]; then
          curl -X PUT -d "${KAFKA_BOOTSTRAP_SERVERS}" ${CONSUL_HTTP_ADDR}/v1/kv/kafka/bootstrap_servers
          echo "Pushed kafka/bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS}"
        else
          echo "KAFKA_BOOTSTRAP_SERVERS not set in .env."
        fi
        # Kafka queue name (topic)
        if [ -n "${KAFKA_TOPIC}" ]; then
          curl -X PUT -d "${KAFKA_TOPIC}" ${CONSUL_HTTP_ADDR}/v1/kv/kafka/topic
          echo "Pushed kafka/topic: ${KAFKA_TOPIC}"
        else
          echo "KAFKA_TOPIC not set in .env."
        fi

        echo "Kafka configuration push complete."
      '
    networks:
      - lab5-network


  # Facade Service
  facade-service:
    container_name: facade-service
    build: ./facade_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - lab5-network
    depends_on:
      consul-init:
        condition: service_completed_successfully
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

  # Messages Service
  messages-service-1:
    container_name: messages-service-1
    build: ./messages_service
    ports:
      - "8200:8002"
    env_file:
      - .env
    environment:
      - KAFKA_GROUP_ID="messages-service-group-1"
    networks:
      - lab5-network
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

  messages-service-2:
    container_name: messages-service-2
    build: ./messages_service
    ports:
      - "8201:8002"
    env_file:
      - .env
    environment:
      - KAFKA_GROUP_ID="messages-service-group-2"
    networks:
      - lab5-network
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-1
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    ports:
      - "9092:9092"
    networks:
      - lab5-network
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-2:
    image: bitnami/kafka:latest
    container_name: kafka-2
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    ports:
      - "9093:9092"
    networks:
      - lab5-network
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-3:
    image: bitnami/kafka:latest
    container_name: kafka-3
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    ports:
      - "9094:9092"
    networks:
      - lab5-network
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Logging Service replicas
  logging-service-1:
    container_name: logging-service-1
    build: ./logging_service
    ports:
      - "8001:8001"  # gRPC port
    env_file:
      - .env
    environment:
      - HAZELCAST_NODE=hz-node-1
      - CLUSTER_NAME=${CLUSTER_NAME}
    depends_on:
      - hz-node-1
      - consul
    networks:
      - lab5-network

  logging-service-2:
    container_name: logging-service-2
    build: ./logging_service
    ports:
      - "8002:8001"
    env_file:
      - .env
    environment:
      - HAZELCAST_NODE=hz-node-2
      - CLUSTER_NAME=${CLUSTER_NAME}
    depends_on:
      - hz-node-2
      - consul
    networks:
      - lab5-network

  logging-service-3:
    container_name: logging-service-3
    build: ./logging_service
    ports:
      - "8003:8001"
    env_file:
      - .env
    environment:
      - HAZELCAST_NODE=hz-node-3
      - CLUSTER_NAME=${CLUSTER_NAME}
    depends_on:
      - hz-node-3
      - consul
    networks:
      - lab5-network

  hazelcast-mc:
    image: hazelcast/management-center:latest
    container_name: hazelcast-mc
    environment:
      - MC_DEFAULT_CLUSTER=${CLUSTER_NAME}
      - MC_DEFAULT_CLUSTER_MEMBERS=hz-node-1,hz-node-2,hz-node-3
      - MC_ADMIN_USER=${MC_ADMIN_USER}
      - MC_ADMIN_PASSWORD=${MC_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - lab5-network

  # Hazelcast Nodes
  hz-node-1:
    image: hazelcast/hazelcast:5-slim
    container_name: hz-node-1
    environment:
      - HZ_NETWORK_PUBLICADDRESS=${PUBLIC_IP}:5701
      - HZ_CLUSTERNAME=${CLUSTER_NAME}
    ports:
      - "5701:5701"
    networks:
      - lab5-network
        

  hz-node-2:
    image: hazelcast/hazelcast:5-slim
    container_name: hz-node-2
    environment:
      - HZ_NETWORK_PUBLICADDRESS=${PUBLIC_IP}:5702
      - HZ_CLUSTERNAME=${CLUSTER_NAME}
    ports:
      - "5702:5701"
    networks:
      - lab5-network
  
  hz-node-3:
    image: hazelcast/hazelcast:5-slim
    container_name: hz-node-3
    environment:
      - HZ_NETWORK_PUBLICADDRESS=${PUBLIC_IP}:5703
      - HZ_CLUSTERNAME=${CLUSTER_NAME}
    ports:
      - "5703:5701"
    networks:
      - lab5-network


networks:
  lab5-network:
    name: lab5-network
    driver: bridge
